### ISSUE TITLE
Support Jetson?

### ISSUE THREAD

**Issue by johnnynunez** [NVIDIA/JAX-Toolbox#1034]
I'm doing a docker in jetson-containers but XLA not support natively jetson, only sbsa.
So i'm building taking account paths of jetpack.
But i get that cuda.h not found.

```bash
python3 build/build.py --enable_cuda --cuda_compute_capabilities=sm_87 --bazel_options=--repo_env=LOCAL_CUDA_PATH="/usr/local/cuda-12.2" --bazel_options=--repo_env=LOCAL_CUDNN_PATH="/usr/lib/aarch64-linux-gnu"
```

**Comment by sbhavani** [comment]
@johnnynunez, have you checked out the [NGC catalog for TensorFlow](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow)? We have a container for Jetson/iGPU (nvcr.io/nvidia/tensorflow:24.08-tf2-py3-igpu), which might serve as a good starting point. These containers also undergo XLA-specific testing.

**Comment by johnnynunez** [comment]
I think that the problem is jax, I have the container and don't compile it. I will wait for next release because, they are some bugs for arm, I mean sbsa and jetson
