### ISSUE TITLE
XLA_FLAGS to enable LHS should be exported in JAX container

### ISSUE THREAD

**Issue by nluehr** [NVIDIA/JAX-Toolbox#109]
Similar to the environment variables in issue https://github.com/NVIDIA/JAX-Toolbox/issues/105, the following XLA flags should be enabled by default to provide out-of-the-box performance at least for paxml models (and probably for all JAX-based containers).

```
XLA_FLAGS=--xla_gpu_enable_latency_hiding_scheduler=true --xla_gpu_enable_async_all_gather=true --xla_gpu_enable_async_reduce_scatter=true --xla_gpu_enable_triton_gemm=false
```

**Comment by terrykong** [comment]
@nluehr Given that these are going to be tested for paxml models, should we set these for the pax containers first, and move them to jax after we test them for other models/frameworks?

> (and probably for all JAX-based containers)

Do you expect the perf to be the same or better? Or is it possible that by enabling these, other models can become less performant?

**Comment by nouiz** [comment]
Maybe we should check with Google why they aren't enabled by default?
