### ISSUE TITLE
Store workflow defaults like repo paths in this repository's variables

### ISSUE THREAD

**Issue by andportnoy** [NVIDIA/JAX-Toolbox#160]
Currently they are duplicated as literals multiple times across different workflows. It's good to have a literal default repeated in a Dockerfile though for times when you need to build/reproduce something locally.

Defaults like CUDA image version could be stored in two locations: repo variable and Dockerfile ARG default.

**Comment by yhtang** [comment]
+1 for having single sources of truth for default values.
However, there may be better solutions than CI/CD variables because they will make the Dockerfiles no longer self-contained.
