### ISSUE TITLE
Add nsys to $PATH

### ISSUE THREAD

**Issue by abhinavgoel95** [NVIDIA/JAX-Toolbox#170]
Could we add `/opt/nvidia/nsight-compute/2023.1.1/host/target-linux-x64/nsys` to $PATH?

**Comment by terrykong** [comment]
It looks like should be added to the path in the base CUDA container:
```
$ docker run --rm -it --entrypoint='' nvidia/cuda:12.2.0-devel-ubuntu22.04 sh -c 'echo $PATH'
/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
@yhtang , do you know why it's not set in the base CUDA container?

**Comment by sbhavani** [comment]
+1 can't run `nsys --version`

**Comment by yhtang** [comment]
nsys is inherited from `nvidia/cuda`. I'm not sure why it was not added to PATH there. I will add it in `jax-toolbox:base` as an emergency fix and then discuss with the maintainer of `nvidia/cuda` to understand if it can be added there to benefit more users.

**Comment by yhtang** [comment]
@abhinavgoel95 Could you please pull the new container from [this workflow run](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5967773973) and let me know if you can access `nsys` as expected?
