### ISSUE TITLE
Dockerfile.jax,pax and t5x try install flax.

### ISSUE THREAD

**Issue by nouiz** [NVIDIA/JAX-Toolbox#328]
The output of some grep:
```
Dockerfile.jax:RUN { pip install flax || true; } && rm -rf ~/.cache/*
Dockerfile.pax.amd64:ADD install-flax.sh /usr/local/bin
Dockerfile.pax.amd64:install-flax.sh --defer
Dockerfile.t5x:ADD install-flax.sh /usr/local/bin
Dockerfile.t5x:install-flax.sh
```

Dockerfile.jax try to install flax, but allows it to fail.
Then t5x and pax Dockerfile install it via install-flax.sh

We should be more consistent. Should we not try to install it in the JAX container?
Or we should use the install-flax.sh file?
This also seem to bypass the pinning of the flax version in the JAX container.

**Comment by yhtang** [comment]
This behavior will be overhaul by my WIP: https://github.com/NVIDIA/JAX-Toolbox/tree/add-pip-compile
