### ISSUE TITLE
Need to cancel orphaned SLURM jobs

### ISSUE THREAD

**Issue by yhtang** [NVIDIA/JAX-Toolbox#415]
Currently, if a multi-node CI job submits a SLURM job and then gets canceled while waiting for the SLURM job to run, the SLURM job will become orphaned: it will be left in the queue to run, thus wasting computing resources, even though its result will not be collected. To fix this, we need to:

1. Keep track of the submitted SLURM job id, e.g. using a step output variable
2. Define a cancellation step that runs if the job is canceled using the `if: canceled ()` condition to properly remove the SLURM job.

This will help to reduce the congestion in our CI cluster, especially when repeated updates to a PR cause the SLURM queue to be flooded with orphaned CI jobs.

**Comment by terrykong** [comment]
I don't know what signal gets sent, but would a simple `trap` be less complex solution?

**Comment by olupton** [comment]
https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run
> For steps that need to be canceled, the runner machine sends SIGINT/Ctrl-C to the step's entry process (node for javascript action, docker for container action, and bash/cmd/pwd when using run in a step). If the process doesn't exit within 7500 ms, the runner will send SIGTERM/Ctrl-Break to the process, then wait for 2500 ms for the process to exit. If the process is still running, the runner kills the process tree.

so the bash script could catch SIGINT and cancel the Slurm job?
