### ISSUE TITLE
Pallas images don't have triton/jax-triton installed

### ISSUE THREAD

**Issue by davisyoshida** [NVIDIA/JAX-Toolbox#470]
Running the following seems to show that the pallas image doesn't actually include the dependencies. Is something additional required to use this image?

```bash
docker run -i --runtime=nvidia --gpus all -t ghcr.io/nvidia/jax:nightly-pallas-2024-01-13
...
$ pip freeze
absl-py==2.0.0
annotated-types==0.6.0
build==1.0.3
chex==0.1.85
click==8.1.7
etils==1.6.0
-e git+https://github.com/google/flax.git@d58e6dde1b659017e7fb8af5989c22e2e86b9f00#egg=flax
fsspec==2023.12.2
importlib-resources==6.1.1
-e git+https://github.com/google/jax.git@b8b119d9b9df4d4d3ca5522a2063e90dcffccb34#egg=jax
jaxlib @ file:///opt/jax/dist/jaxlib-0.4.24.dev20240113-cp310-cp310-manylinux2014_x86_64.whl#sha256=81e26e1f2f4608a9d6f14d823965bd2cdd10d42e2ebbe240b90f20cb23c352e3
markdown-it-py==3.0.0
mdurl==0.1.2
ml-dtypes==0.3.2
msgpack==1.0.7
nest-asyncio==1.5.8
numpy==1.26.3
opt-einsum==3.3.0
optax==0.1.7
orbax-checkpoint==0.4.8
packaging==23.2
pip-tools==7.3.0
protobuf==4.25.2
pydantic==2.5.3
pydantic_core==2.14.6
Pygments==2.17.2
pyproject_hooks==1.0.0
PyYAML==6.0.1
rich==13.7.0
scipy==1.11.4
tensorstore==0.1.52
tomli==2.0.1
toolz==0.12.0
transformer-engine @ file:///opt/transformer-engine/dist/transformer_engine-1.3.0.dev0+daad219-cp310-cp310-linux_x86_64.whl#sha256=efd18bb195aa81ad093153c9410f9cabd68a5c7d9ec182252582c039c2ae6714
typing_extensions==4.9.0
zipp==3.17.0
```

**Comment by olupton** [comment]
Thanks for the report. You're right that there's a glitch here, which the CI test has managed not to flag.
Unfortunately this is hiding some other issues, including the one you reported at https://github.com/google/jax/discussions/19353#discussioncomment-8129678, which we'll need to find a solution for.

**Comment by olupton** [comment]
This specific issue was fixed in https://github.com/NVIDIA/JAX-Toolbox/pull/471, and the other issue I linked to above was fixed in https://github.com/google/jax/pull/19377.
Unfortunately there are still issues running the Pallas tests with the current HEADs (but it's **possible** that the current nightly Pallas wheels will work for some things).
