### ISSUE TITLE
 Can't find UUID for CUDA device

### ISSUE THREAD

**Issue by mitkotak** [NVIDIA/JAX-Toolbox#669]
Any thoughts on how to resolve this issue ?

```
FATAL ERROR: /dvs/p4/build/sw/devtools/Agora/Rel/CUDA12.3/QuadD/Target/quadd_d/quadd_d/jni/EventSource/Trace.cpp(1855): Throw in function QuadDCommon::Uuid QuadDDaemon::EventSource::Trace::GetCudaDeviceUuidForTimestamp(QuadDCommon::ProcessId, const ConstTraceEvent&, uint64_t) const
Dynamic exception type: boost::wrapexcept<QuadDCommon::InternalErrorException>
std::exception::what: InternalErrorException
[QuadDCommon::tag_message*] = Can't find UUID for CUDA device 0 (PID 216076)
```

So far I have been able to resolve it by running the profiling again and again until it works but was wondering what's causing it. Sorry for not having a MWE since this one pops up randomly.

**Comment by olupton** [comment]
IIRC this only appears in one, older Nsight Systems version. Can you upgrade? 2024.2 was released fairly recently.

**Comment by mitkotak** [comment]
Yup it worked :)
