### ISSUE TITLE
PAX MGMN nightly silently failing

### ISSUE THREAD

**Issue by yhtang** [NVIDIA/JAX-Toolbox#93]
Some of the [recent jobs](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5321251146/jobs/9636123087) failed, but the workflow runs had green lights.

This is actually our desired behavior since nightly pipeline's own logic is correctly executed. However, one thing is missing: automatic ticket generation.

We need to create a postprocessing script that scans the run log, and file issues when the desired output is not found.

**Comment by terrykong** [comment]
I changed the title and split this issue so that the issue creation can be tracked in a [separate issue](https://github.com/NVIDIA/JAX-Toolbox/issues/136). Currently pax test failures no longer slip by undetected and we have a badge that shows how many tests have failed/passed
